Abort compilation if OPENWISP_CONF is unset, fixes #37

diff --git a/meta/openwisp-fw/Makefile b/meta/openwisp-fw/Makefile
--- a/meta/openwisp-fw/Makefile
+++ b/meta/openwisp-fw/Makefile
@@ -73,15 +73,15 @@ define Package/openwisp-fw-base/install
 	$(CP) -r ./files/* $(1)/
 
 	#unpack external configuration
-	if [ -z "$(OPENWISP_CONF)" ]; then exit 2; fi      # system unconfigured
 	if [ -d $(OPENWISP_CONF) ]; then \
 		cp -fr $(OPENWISP_CONF) $(1)/; \
-	fi
-	if [ -f $(OPENWISP_CONF) ]; then \
+	elif [ -f $(OPENWISP_CONF) ]; then \
 		tar xvzf $(OPENWISP_CONF) -C $(1)/; \
-	fi
-	if [ `echo $(OPENWISP_CONF) | grep '^http' -` ]; then \
+	elif [ `echo $(OPENWISP_CONF) | grep '^http' -` ]; then \
 		wget $(OPENWISP_CONF) -qO - | tar xvz -C $(1)/; \
+	elif \
+		echo "ERROR: Missed configuration of OPENWISP_CONF variable"; \
+		exit 2; \
 	fi
 
 	git describe --tags --always || echo 'no-git-version' > $(1)/etc/openwisp_version
